### ISSUE TITLE
LLE stops working if "BioD_Arvlvl3_230_Mainframe" is visible (not loaded) in LE2

### ISSUE THREAD

**Issue by mkhaar** [Mgamerz/ME3Explorer#397] opened 2023-09-15 05:02 UTC
**Describe the bug**
Live Level Editor stops working, making the game hang for a couple of seconds, and being unable to retrieve loaded and visible files and their respective actors, the moment "BioD_Arvlvl3_230_Mainframe.pcc" (LE2) becomes visible, either by forcing its streaming through the console, or activating a BioTriggerStream that makes it visible.

**To Reproduce**

Have LLE opened and initialized and load a savegame on Arrival before launching the asteroid (Save file at the area can be found [here](https://cdn.discordapp.com/attachments/593673315839770626/1150316215345106954/QuickSave.pcsav)). For ease, have the Streaming Levels ASI HUD installed. The moment you proceed further and BioD_Arvlvl3_230_Mainframe goes from yellow loaded, to green visible; the game will start stuttering for a few seconds (stutter **not** related to streaming issues with orange lines appearing). Al-tab your game and you will find a LEX pop-up error: message attached below. At this moment you will realize LLE has no level files on the list anymore. Also, gameplay resumes back to normal. Trying to Manually Regenerate Actor List will produce a new error message and the same stuttery behavior on the game.

Streaming that level out through the console, or pulling back, so it goes back to only loaded and not visible; and then trying to Manually Regenerate Actor List again, it will work, with no LEX errors, nor game stutters. Streaming in the level, will once again cause the exact same behavior.

I have tested this both with a Bioware vanilla file and modded one, I get the same behavior, so I do not think it is any modded issue. Moreover, running resolve imports, check bad references, check for uscript errors or trying to deploy any mod with the file on it does not prompt any issue.

**Expected behavior**
LLE would not throw an error and should let you be used when the file is visible.

**Screenshots and files used to replicate this**
BioD_Arvlvl3_230_Mainframe --> LE2 Arrival DLC

**Version information:**
I compile my own toolset from source, but I always do it from nightly. Currently running on **6.3 DEBUG 9/13/2023**.

**Stack trace**
```
JsonReaderException: After parsing a value an unexpected character was encountered: M. Path '[6].Actors[0].Tag', line 1, position 88966.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at LegendaryExplorer.Tools.LiveLevelEditor.LELiveLevelEditorWindow.UpdateLevels(String json) in C:\Users\evdhy\Source\Repos\LegendaryExplorer\LegendaryExplorer\LegendaryExplorer\Tools\LiveLevelEditor\LELiveLevelEditorWindow.xaml.cs:line 451
   at LegendaryExplorer.Tools.LiveLevelEditor.LELiveLevelEditorWindow.GameControllerOnReceiveMessage(String msg) in C:\Users\evdhy\Source\Repos\LegendaryExplorer\LegendaryExplorer\LegendaryExplorer\Tools\LiveLevelEditor\LELiveLevelEditorWindow.xaml.cs:line 347
   at LegendaryExplorer.GameInterop.InteropTargets.InteropTarget.RaiseReceivedMessage(String message) in C:\Users\evdhy\Source\Repos\LegendaryExplorer\LegendaryExplorer\LegendaryExplorer\GameInterop\InteropTargets\InteropTarget.cs:line 73
   at LegendaryExplorer.GameInterop.GameController.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in C:\Users\evdhy\Source\Repos\LegendaryExplorer\LegendaryExplorer\LegendaryExplorer\GameInterop\GameController.cs:line 93
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
```

**Other information**
N/A

**Comment by SirCxyrtyx** [comment] 2023-09-17 03:40
The problem is that `#1759  TheWorld.PersistentLevel.Note_0` has quotation marks in its Tag, and the ASI fails to escape them when encoding the JSON. This is my punishment for thinking I can roll my own C++ JSON encoder. 😅  

Fixing this will require updating the Interop ASI, which may take a bit. A simple workaround in the meantime would be to remove the quotation marks from the Tag property of `#1759  TheWorld.PersistentLevel.Note_0`.

**Comment by mkhaar** [comment] 2023-09-22 10:38
Forgot to reply, that this worked out. Good to know, and no rush in fixing it, if the workaround just works. 👍🏻

**Comment by mkhaar** [comment] 2023-10-30 07:56
The bug seems to be back as of today, running on the latest nightly as built from source (6.3; 10/29/23):

 ```JsonReaderException: After parsing a value an unexpected character was encountered: M. Path '[7].Actors[0].Tag', line 1, position 117000.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at LegendaryExplorer.Tools.LiveLevelEditor.LELiveLevelEditorWindow.UpdateLevels(String json) in C:\Users\evdhy\Source\Repos\LegendaryExplorer\LegendaryExplorer\LegendaryExplorer\Tools\LiveLevelEditor\LELiveLevelEditorWindow.xaml.cs:line 451
   at LegendaryExplorer.Tools.LiveLevelEditor.LELiveLevelEditorWindow.GameControllerOnReceiveMessage(String msg) in C:\Users\evdhy\Source\Repos\LegendaryExplorer\LegendaryExplorer\LegendaryExplorer\Tools\LiveLevelEditor\LELiveLevelEditorWindow.xaml.cs:line 347
   at LegendaryExplorer.GameInterop.InteropTargets.InteropTarget.RaiseReceivedMessage(String message) in C:\Users\evdhy\Source\Repos\LegendaryExplorer\LegendaryExplorer\LegendaryExplorer\GameInterop\InteropTargets\InteropTarget.cs:line 73
   at LegendaryExplorer.GameInterop.GameController.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in C:\Users\evdhy\Source\Repos\LegendaryExplorer\LegendaryExplorer\LegendaryExplorer\GameInterop\GameController.cs:line 93
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by SirCxyrtyx** [comment] 2023-10-30 17:36
Not _back_ so much as never fixed 😅. I committed a fix to the asi repo, but LEX hasn’t been updated to use new asis.

**Comment by mkhaar** [comment] 2023-10-31 12:23
Oh! My bad then. Sorry, I will keep using the workaround 😉

**Comment by Mgamerz** [comment] 2023-11-24 22:39
This should be fixed with the current ASI manifest.

**Closed as completed by Mgamerz** 2023-11-24 22:39 UTC
